name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: testing
    steps:
    - uses: actions/checkout@v2
  build1:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - uses: actions/checkout@v2
   
